services:
 - docker
language: php
php:
  - '7.2'
git:
  depth: false

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_script:
  - sudo pip install shyaml
  - docker-compose -f docker-compose.travis.yml up --force --build -d
  - docker ps
  - docker-compose -f docker-compose.travis.yml exec cli composer install
  - docker-compose -f docker-compose.travis.yml exec cli /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush site-install -y config_installer

script:
  - docker-compose -f docker-compose.travis.yml exec cli bash -c "vendor/bin/phpunit -c ."

deploy:
  provider: script
  script: bash scripts/travis/deploy.sh
